# SPDX-License-Identifier: MIT

require conf/distro/cassini.conf

DISTRO = "auto-ad-nexios"
DISTRO_NAME = "Auto AD Nexios"

# Auto AD Nexios requires the PREEMPT_RT kernel profile.
PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-rt"

# Auto AD Nexios is based on Cassini and keeps EWAOL image-feature
# compatibility for the Arm Auto Solutions baremetal image flow.
BASE_DISTRO = "cassini"
DISTROOVERRIDES .= ":ewaol:${BASE_DISTRO}"

CASSINI_ADMIN_ACCOUNT = "ewaol"
DISTRO_FEATURES:append = " ewaol-cloud"
DISTRO_FEATURES:append:auto-ad-nexios = " security integrity overlayfs"

IMAGE_CLASSES:append:auto-ad-nexios = " dm-verity-img"
DM_VERITY_IMAGE:auto-ad-nexios = "nexios-image"
DM_VERITY_IMAGE_TYPE:auto-ad-nexios = "ext4"
DM_VERITY_SEPARATE_HASH:auto-ad-nexios = "0"
INITRAMFS_IMAGE:auto-ad-nexios = "nexios-initramfs-image"
INITRAMFS_FSTYPES:auto-ad-nexios = "cpio.gz"

OVERLAYFS_ETC_MOUNT_POINT:auto-ad-nexios = "/rootrw"
OVERLAYFS_ETC_FSTYPE:auto-ad-nexios = "ext4"
OVERLAYFS_ETC_DEVICE:auto-ad-nexios = "LABEL=rootrw"
OVERLAYFS_ETC_MOUNT_OPTIONS:auto-ad-nexios = "defaults"
OVERLAYFS_ETC_CREATE_MOUNT_DIRS:auto-ad-nexios = "0"

USER_CLASSES:append = " ewaol-features"
VIRTUAL-RUNTIME_ota_update = "no-ota"

WKS_FILE:apollo-fvp:auto-ad-nexios = "apollo-fvp-auto-ad-nexios-ab.wks.in"
WKS_FILE_DEPENDS:append:apollo-fvp:auto-ad-nexios = " auto-ad-nexios-boot-state"

TEST_SUITES:apollo-fvp:auto-ad-nexios = "\
    ping \
    ssh \
    test_00_aspen_boot \
    test_00_rse \
    test_00_secure_partition \
    test_01_auto_ad_nexios_uki_boot \
    test_02_safety_boot \
    test_10_linuxboot \
    test_20_aspen_ap_dsu \
    test_30_configurable_pc_cores \
    fvp_boot \
    fvp_devices \
    "
