#!/usr/bin/env bash
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
POKY_DIR="${WORKSPACE_DIR}/layers/poky"

BUILD_DIR="${BUILD_DIR:-${WORKSPACE_DIR}/build}"
TEMPLATECONF="${TEMPLATECONF:-${WORKSPACE_DIR}/hsoc-stack/yocto/meta-hsoc-auto-solutions/conf/templates/apollo-fvp}"

DM_VERITY_MODE="${APOLLO_DM_VERITY:-}"
DRY_RUN=0

usage() {
    cat <<'EOF'
Usage: ./build.sh [options]

Build the Apollo FVP Yocto nexios-image.

Options:
  --dm-verity=on|off      Build through the matching Yocto multiconfig.
  --dm-verity on|off      Same as --dm-verity=on|off.
  --with-dm-verity        Alias for --dm-verity=on.
  --without-dm-verity     Alias for --dm-verity=off.
  --dry-run               Print the BitBake command without running it.
  -h, --help              Show this help.

Environment:
  APOLLO_DM_VERITY=on|off Select the same multiconfig as --dm-verity.
EOF
}

normalize_dm_verity_mode() {
    local mode="$1"

    case "${mode}" in
        ""|default)
            echo ""
            ;;
        1|on|true|yes|enabled|enable)
            echo "on"
            ;;
        0|off|false|no|disabled|disable)
            echo "off"
            ;;
        *)
            echo "error: invalid dm-verity mode '${mode}'" >&2
            exit 2
            ;;
    esac
}

while (($#)); do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        --dm-verity=*)
            DM_VERITY_MODE="${1#*=}"
            shift
            ;;
        --dm-verity)
            [[ $# -ge 2 ]] || {
                echo "error: --dm-verity requires on or off" >&2
                exit 2
            }
            DM_VERITY_MODE="$2"
            shift 2
            ;;
        --with-dm-verity)
            DM_VERITY_MODE="on"
            shift
            ;;
        --without-dm-verity)
            DM_VERITY_MODE="off"
            shift
            ;;
        *)
            echo "error: unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

DM_VERITY_MODE="$(normalize_dm_verity_mode "${DM_VERITY_MODE}")"

host_cpus() {
    nproc 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 1
}

host_mem_mib() {
    awk '/^MemTotal:/ { print int($2 / 1024); exit }' /proc/meminfo 2>/dev/null || echo 0
}

auto_build_threads() {
    local cpus mem_mib mem_threads threads

    cpus="$(host_cpus)"
    mem_mib="$(host_mem_mib)"

    if [[ "${mem_mib}" -gt 0 ]]; then
        mem_threads=$((mem_mib / 2048))
        [[ "${mem_threads}" -lt 1 ]] && mem_threads=1
    else
        mem_threads="${cpus}"
    fi

    threads="${cpus}"
    [[ "${threads}" -gt "${mem_threads}" ]] && threads="${mem_threads}"
    [[ "${threads}" -gt 6 ]] && threads=6
    [[ "${threads}" -lt 1 ]] && threads=1

    echo "${threads}"
}

bitbake_network_sandbox_supported() {
    python3 - <<'PY'
import ctypes
import os
import sys

libc = ctypes.CDLL("libc.so.6")
clone_newuser = 0x10000000
clone_newnet = 0x40000000

ret = libc.unshare(clone_newnet | clone_newuser)
if ret != 0:
    sys.exit(1)

try:
    with open("/proc/self/uid_map", "w", encoding="utf-8") as uid_map:
        uid_map.write(f"{os.getuid()} {os.getuid()} 1")
    with open("/proc/self/setgroups", "w", encoding="utf-8") as setgroups:
        setgroups.write("deny")
    with open("/proc/self/gid_map", "w", encoding="utf-8") as gid_map:
        gid_map.write(f"{os.getgid()} {os.getgid()} 1")
except OSError:
    sys.exit(1)
PY
}

if [[ ! -f "${POKY_DIR}/oe-init-build-env" ]]; then
    echo "error: missing ${POKY_DIR}/oe-init-build-env" >&2
    exit 1
fi

if [[ ! -d "${TEMPLATECONF}" ]]; then
    echo "error: missing TEMPLATECONF directory: ${TEMPLATECONF}" >&2
    exit 1
fi

export TEMPLATECONF

# shellcheck source=/dev/null
set +u
source "${POKY_DIR}/oe-init-build-env" "${BUILD_DIR}"
set -u

BITBAKE_ARGS=()
BITBAKE_TARGET="nexios-image"

case "${DM_VERITY_MODE}" in
    on)
        DM_VERITY_MC="apollo-fvp-dm-verity"
        ;;
    off)
        DM_VERITY_MC="apollo-fvp-no-dm-verity"
        ;;
    *)
        DM_VERITY_MC=""
        ;;
esac

if [[ -n "${DM_VERITY_MC}" ]]; then
    MULTICONFIG_CONF="${PWD}/conf/apollo-dm-verity-multiconfig.conf"
    {
        echo "#"
        echo "# Generated by build.sh."
        echo "# Select the Apollo dm-verity Yocto multiconfig."
        echo "#"
        echo "BBMULTICONFIG = \"${DM_VERITY_MC}\""
    } >"${MULTICONFIG_CONF}"
    BITBAKE_ARGS+=(-R "${MULTICONFIG_CONF}")
    BITBAKE_TARGET="mc:${DM_VERITY_MC}:nexios-image"
    echo "notice: dm-verity mode '${DM_VERITY_MODE}' uses multiconfig ${DM_VERITY_MC}" >&2
fi

if [[ "${APOLLO_AUTO_RESOURCE_LIMITS:-1}" != "0" || -n "${APOLLO_BUILD_THREADS:-}" || -n "${APOLLO_PARALLEL_MAKE:-}" ]]; then
    AUTO_THREADS="$(auto_build_threads)"
    BUILD_THREADS="${APOLLO_BUILD_THREADS:-${AUTO_THREADS}}"
    PARALLEL_MAKE_VALUE="${APOLLO_PARALLEL_MAKE:--j${AUTO_THREADS}}"
    RESOURCE_CONF="${PWD}/conf/apollo-bitbake-resources.conf"
    {
        echo "#"
        echo "# Generated by build.sh."
        echo "# Set APOLLO_AUTO_RESOURCE_LIMITS=0 to use BitBake defaults."
        echo "#"
        echo "BB_NUMBER_THREADS = \"${BUILD_THREADS}\""
        echo "PARALLEL_MAKE = \"${PARALLEL_MAKE_VALUE}\""
    } >"${RESOURCE_CONF}"
    BITBAKE_ARGS+=(-R "${RESOURCE_CONF}")
    echo "notice: using BitBake resource limits from ${RESOURCE_CONF}" >&2
    echo "notice: BB_NUMBER_THREADS=${BUILD_THREADS} PARALLEL_MAKE=${PARALLEL_MAKE_VALUE}" >&2
fi

if ! bitbake_network_sandbox_supported; then
    HOST_CONF="${PWD}/conf/apollo-bitbake-host.conf"
    cat >"${HOST_CONF}" <<'EOF'
#
# Generated by build.sh for hosts where bitbake-worker cannot write
# /proc/self/uid_map after unshare(CLONE_NEWUSER | CLONE_NEWNET).
#
INHERIT += "apollo-bitbake-network-sandbox"
APOLLO_BITBAKE_DISABLE_NETWORK_SANDBOX = "1"
EOF
    BITBAKE_ARGS+=(-R "${HOST_CONF}")
    echo "notice: BitBake worker network sandbox is unsupported; using ${HOST_CONF}" >&2
fi

if [[ "${DRY_RUN}" == "1" ]]; then
    printf 'bitbake'
    printf ' %q' "${BITBAKE_ARGS[@]}" "${BITBAKE_TARGET}"
    printf '\n'
    exit 0
fi

bitbake "${BITBAKE_ARGS[@]}" "${BITBAKE_TARGET}"
