#!/usr/bin/env bash
#
# SPDX-License-Identifier: MIT
#

set -euo pipefail

WORKSPACE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
POKY_DIR="${WORKSPACE_DIR}/layers/poky"

BUILD_DIR="${BUILD_DIR:-${WORKSPACE_DIR}/build}"
TEMPLATECONF="${TEMPLATECONF:-${WORKSPACE_DIR}/hsoc-stack/yocto/meta-hsoc-apollo/conf/templates/apollo-fvp}"

bitbake_network_sandbox_supported() {
    python3 - <<'PY'
import ctypes
import os
import sys

libc = ctypes.CDLL("libc.so.6")
clone_newuser = 0x10000000
clone_newnet = 0x40000000

ret = libc.unshare(clone_newnet | clone_newuser)
if ret != 0:
    sys.exit(1)

try:
    with open("/proc/self/uid_map", "w", encoding="utf-8") as uid_map:
        uid_map.write(f"{os.getuid()} {os.getuid()} 1")
    with open("/proc/self/setgroups", "w", encoding="utf-8") as setgroups:
        setgroups.write("deny")
    with open("/proc/self/gid_map", "w", encoding="utf-8") as gid_map:
        gid_map.write(f"{os.getgid()} {os.getgid()} 1")
except OSError:
    sys.exit(1)
PY
}

if [[ ! -f "${POKY_DIR}/oe-init-build-env" ]]; then
    echo "error: missing ${POKY_DIR}/oe-init-build-env" >&2
    exit 1
fi

if [[ ! -d "${TEMPLATECONF}" ]]; then
    echo "error: missing TEMPLATECONF directory: ${TEMPLATECONF}" >&2
    exit 1
fi

export TEMPLATECONF

# shellcheck source=/dev/null
set +u
source "${POKY_DIR}/oe-init-build-env" "${BUILD_DIR}"
set -u

BITBAKE_ARGS=()
if [[ -n "${APOLLO_BUILD_THREADS:-}" || -n "${APOLLO_PARALLEL_MAKE:-}" ]]; then
    RESOURCE_CONF="${PWD}/conf/apollo-bitbake-resources.conf"
    {
        echo "#"
        echo "# Generated by build.sh when APOLLO_BUILD_THREADS or"
        echo "# APOLLO_PARALLEL_MAKE is set in the environment."
        echo "#"
        if [[ -n "${APOLLO_BUILD_THREADS:-}" ]]; then
            echo "BB_NUMBER_THREADS = \"${APOLLO_BUILD_THREADS}\""
        fi
        if [[ -n "${APOLLO_PARALLEL_MAKE:-}" ]]; then
            echo "PARALLEL_MAKE = \"${APOLLO_PARALLEL_MAKE}\""
        fi
    } >"${RESOURCE_CONF}"
    BITBAKE_ARGS+=(-R "${RESOURCE_CONF}")
    echo "notice: using BitBake resource limits from ${RESOURCE_CONF}" >&2
fi

if ! bitbake_network_sandbox_supported; then
    HOST_CONF="${PWD}/conf/apollo-bitbake-host.conf"
    cat >"${HOST_CONF}" <<'EOF'
#
# Generated by build.sh for hosts where bitbake-worker cannot write
# /proc/self/uid_map after unshare(CLONE_NEWUSER | CLONE_NEWNET).
#
INHERIT += "apollo-bitbake-network-sandbox"
APOLLO_BITBAKE_DISABLE_NETWORK_SANDBOX = "1"
EOF
    BITBAKE_ARGS+=(-R "${HOST_CONF}")
    echo "notice: BitBake worker network sandbox is unsupported; using ${HOST_CONF}" >&2
fi

bitbake "${BITBAKE_ARGS[@]}" baremetal-image
