[Unit]
Requires=bluechi-controller.service
After=bluechi-controller.service

[Container]
Volume=/run/bluechi/bluechi.sock:/run/bluechi/bluechi.sock
PodmanArgs=--cpuset-cpus=2-3

[Service]
AllowedCPUs=2-3
