"""Matching PFDI payload and conditional AutoSD full-system service contracts.

The caller uploads these trusted build artifacts into its private guest staging
directory. Service startup checks real per-CPU diagnostic calls; continued SCP
monitoring is separate evidence and must never be inferred from a running PID.
"""
import hashlib
from pathlib import Path
import re
import shlex
import subprocess


SERVICE = """[Unit]
Description=Apollo full-system AP PFDI diagnostics
ConditionKernelCommandLine=apollo.fullsystem=1
After=local-fs.target systemd-modules-load.service
Before=multi-user.target
StartLimitIntervalSec=60
StartLimitBurst=3

[Service]
Type=simple
ExecStartPre=/usr/sbin/modprobe pfdi_misc pfdi_wait_timeout_ms=1000
ExecStartPre=/usr/libexec/apollo-pfdi-check
ExecStart=/usr/bin/pfdi-sample-app -i -c /etc/pfdi/pfdi_test_config_0.pack
Restart=on-failure
RestartSec=2
TimeoutStartSec=30
TimeoutStopSec=10
KillMode=control-group
StandardOutput=journal+console
StandardError=journal+console

[Install]
WantedBy=multi-user.target
"""

CHECK = """#!/bin/sh
set -eu
# This pack is generated by the four-CPU Apollo Yocto build.
test "$(cat /sys/devices/system/cpu/online)" = 0-3
for cpu in 0 1 2 3; do test -c /dev/cpu/$cpu/pfdi; done
log=/run/apollo-pfdi-startup.log
/usr/bin/pfdi-sample-app -iv -c /etc/pfdi/pfdi_test_config_0.pack -m single > "$log" 2>&1
cat "$log"
# The reference app can return success after an individual online call fails.
if grep -Ei 'failed|\\[error\\]' "$log"; then exit 1; fi
for cpu in 0 1 2 3; do
    grep -E "CPU${cpu}: PFDI Online \\(OnL\\) test \\([0-9]+ - [0-9]+\\) OK" "$log"
done
echo AUTOSD_FULLSYSTEM_PFDI_STARTUP_PASS
"""


def service_files():
    return {"apollo-pfdi.service": SERVICE, "apollo-pfdi-check": CHECK}


def _one(paths, description):
    paths = list(paths)
    if len(paths) != 1:
        raise ValueError(f"Expected one {description}; found {len(paths)}")
    return paths[0].resolve()


def _aarch64(path):
    header = path.read_bytes()[:20]
    if len(header) < 20 or header[:6] != b"\x7fELF\x02\x01" or header[18:20] != b"\xb7\x00":
        raise ValueError(f"Expected AArch64 ELF: {path}")


def pfdi_inputs(build_dir):
    work = Path(build_dir) / "tmp_baremetal/work"
    root = _one(work.glob("*/platform-fault-detection/*/image"), "PFDI image")
    module = _one(work.glob("apollo_qvp-poky-linux/pfdi-misc-mod/*/image/usr/lib/modules/*/updates/pfdi_misc.ko"), "pfdi_misc module")
    vermagic = subprocess.check_output(["modinfo", "-F", "vermagic", str(module)], text=True).strip()
    release = vermagic.split()[0] if vermagic else ""
    if not re.fullmatch(r"[A-Za-z0-9_.+-]+", release) or module.parent.parent.name != release:
        raise ValueError("PFDI module path and vermagic release disagree")
    entries = {
        "pfdi_misc.ko": (module, f"/usr/lib/modules/{release}/updates/pfdi_misc.ko", "0644"),
        "pfdi-sample-app": (root / "usr/bin/pfdi-sample-app", "/usr/bin/pfdi-sample-app", "0755"),
        "pfdi-cli": (root / "usr/bin/pfdi-cli", "/usr/bin/pfdi-cli", "0755"),
        "libpfdi.so.1": ((root / "usr/lib/libpfdi.so.1").resolve(), "/usr/lib64/libpfdi.so.1", "0755"),
        "pfdi_test_config_0.pack": (root / "etc/pfdi/pfdi_test_config_0.pack", "/etc/pfdi/pfdi_test_config_0.pack", "0644"),
    }
    result = {}
    for name, (path, target, mode) in entries.items():
        if name != "pfdi_test_config_0.pack":
            _aarch64(path)
        result[name] = {"path": str(path), "target": target, "mode": mode,
                        "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
    result["pfdi_misc.ko"].update(release=release, vermagic=vermagic)
    return result


def install_commands(inputs, remote, *, prepare_only=False):
    """Return guarded shell commands to append to the provisioning transaction."""
    q = shlex.quote
    release = inputs["pfdi_misc.ko"]["release"]
    commands = ['test "$(id -u)" = 0', '. /etc/os-release; test "$ID" = autosd',
                'test "$(uname -r)" = ' + q(release)]
    if not prepare_only:
        commands.append("grep -qw apollo.fullsystem=1 /proc/cmdline")
    for name, entry in inputs.items():
        source = remote + "/" + name
        commands += ["printf '%s\\n' " + q(entry["sha256"] + "  " + source) + " | sha256sum -c -",
                     "install -D -m " + entry["mode"] + " " + q(source) + " " + q(entry["target"]),
                     "restorecon " + q(entry["target"])]
    for name, target, mode in (("apollo-pfdi.service", "/etc/systemd/system/apollo-pfdi.service", "0644"),
                               ("apollo-pfdi-check", "/usr/libexec/apollo-pfdi-check", "0755")):
        digest = hashlib.sha256(service_files()[name].encode()).hexdigest()
        source = remote + "/" + name
        commands += ["printf '%s\\n' " + q(digest + "  " + source) + " | sha256sum -c -",
                     "install -D -m " + mode + " " + q(source) + " " + q(target), "restorecon " + q(target)]
    commands += ["ldconfig", "/lib/ld-linux-aarch64.so.1 --list /usr/bin/pfdi-sample-app",
                 "depmod -a " + q(release), "systemctl daemon-reload",
                 "systemctl enable apollo-pfdi.service"]
    if prepare_only:
        commands.append("printf '%s\\n' AUTOSD_FULLSYSTEM_PFDI_INSTALLED_NOT_STARTED")
    else:
        commands += ["systemctl restart apollo-pfdi.service",
                     "systemctl is-active --quiet apollo-pfdi.service",
                     "cat /run/apollo-pfdi-startup.log",
                     "printf '%s\\n' AUTOSD_FULLSYSTEM_PFDI_PROVISIONED"]
    return commands
