#
# SPDX-License-Identifier: MIT
#

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-hsoc-apollo-bsp"
BBFILE_PATTERN_meta-hsoc-apollo-bsp = "^${LAYERDIR}/"

LAYERDEPENDS_meta-hsoc-apollo-bsp = "core meta-zena-css-bsp"
LAYERSERIES_COMPAT_meta-hsoc-apollo-bsp = "walnascar"

HSOC_APOLLO_BASE := "${LAYERDIR}/../.."
HSOC_APOLLO_LINUX_SRC ?= "${HSOC_APOLLO_BASE}/components/primary_compute/linux"
HSOC_APOLLO_UBOOT_SRC ?= "${HSOC_APOLLO_BASE}/components/primary_compute/u-boot"
HSOC_APOLLO_TFA_SRC ?= "${HSOC_APOLLO_BASE}/components/primary_compute/trusted-firmware-a"
HSOC_APOLLO_TFM_SRC ?= "${HSOC_APOLLO_BASE}/components/system_mgmt/trusted-firmware-m"
ZENA_CSS_BSP_LAYER ?= "${HSOC_APOLLO_BASE}/../arm-zena-css/yocto/meta-zena-css-bsp"
