#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import UTC, datetime
import json
from pathlib import Path
import shlex
import subprocess
import sys
import time
from typing import Final

from config import Profile, SelectionError, Suite, load_profiles, load_suites, resolve_selectors


EXIT_USAGE: Final = 64
EXIT_FAIL: Final = 1
EXIT_BLOCKED: Final = 2


def _timestamp() -> str:
    return datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")


def _write_json(path: Path, value: dict[str, object] | list[dict[str, object]]) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _log(log_path: Path, message: str) -> None:
    line = f"{datetime.now(UTC).isoformat()} {message}"
    print(line, flush=True)
    with log_path.open("a", encoding="utf-8") as stream:
        stream.write(line + "\n")


def _safe_run_dir(root: Path, requested: str | None, machine: str) -> Path:
    tests_root = (root / "build/tests").resolve()
    run_dir = (root / requested).resolve() if requested else tests_root / f"validation-{machine}-{_timestamp()}"
    if run_dir == tests_root or tests_root not in run_dir.parents:
        raise SelectionError(f"output directory must be below {tests_root}")
    return run_dir


def _conf_text(machine: str, profile: Profile, run_dir: Path, selectors: tuple[str, ...]) -> str:
    value = " ".join(selectors)
    scoped = f":{machine}:{profile.distro}"
    lines = (
        "# Generated by scripts/validation/run_validation.py.",
        f'MACHINE = "{machine}"',
        f'TEST_SUITES = "{value}"',
        f'TEST_SUITES{scoped} = "{value}"',
        f'TEST_TARGET = "{profile.controller}"',
        f'TEST_TARGET{scoped} = "{profile.controller}"',
        f'TEST_LOG_DIR = "{run_dir / "oeqa/logs"}"',
        f'OEQA_JSON_RESULT_DIR = "{run_dir / "oeqa/results"}"',
        f'OEQA_ARTEFACT_DIR = "{run_dir / "oeqa/artifacts"}"',
    )
    return "\n".join(lines) + "\n"


def _record_command(commands: Path, record: dict[str, object]) -> None:
    with commands.open("a", encoding="utf-8") as stream:
        stream.write(json.dumps(record, sort_keys=True) + "\n")


def _run_step(name: str, command: str, root: Path, run_dir: Path, commands: Path, dry_run: bool, log_path: Path) -> bool:
    stdout_log = run_dir / "logs" / f"{name}.stdout.log"
    started = datetime.now(UTC).isoformat()
    _log(log_path, f"START {name}: {command}")
    if dry_run:
        _record_command(commands, {"name": name, "command": command, "status": "planned", "started_at": started, "finished_at": datetime.now(UTC).isoformat(), "duration_s": 0.0, "stdout_log": str(stdout_log)})
        _log(log_path, f"DONE {name}: planned")
        return True
    started_clock = time.monotonic()
    with stdout_log.open("w", encoding="utf-8") as stream:
        process = subprocess.Popen(
            ["bash", "-o", "pipefail", "-c", command],
            cwd=root,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        assert process.stdout is not None
        for line in process.stdout:
            stream.write(line)
            _log(log_path, f"PROGRESS {name}: {line.rstrip()}")
        code = process.wait()
    duration = round(time.monotonic() - started_clock, 6)
    status = "passed" if code == 0 else "failed"
    _record_command(commands, {"name": name, "command": command, "status": status, "exit_code": code, "started_at": started, "finished_at": datetime.now(UTC).isoformat(), "duration_s": duration, "stdout_log": str(stdout_log)})
    _log(log_path, f"DONE {name}: {status} ({duration}s)")
    return code == 0


def _parse_assignments(path: Path) -> dict[str, str]:
    assignments: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        for key in ("TEST_SUITES", "TEST_TARGET"):
            prefix = f'{key}="'
            if line.startswith(prefix) and line.endswith('"'):
                assignments[key] = line.removeprefix(prefix)[:-1]
    return assignments


def _verify_parse(run_dir: Path, profile: Profile, selectors: tuple[str, ...], dry_run: bool) -> bool:
    expected = {"TEST_SUITES": " ".join(selectors), "TEST_TARGET": profile.controller}
    if dry_run:
        _write_json(run_dir / "parse-verification.json", {"status": "planned", "expected": expected})
        return True
    actual = _parse_assignments(run_dir / "logs/parse.stdout.log")
    verified = all(actual.get(key) == value for key, value in expected.items())
    _write_json(run_dir / "parse-verification.json", {"status": "passed" if verified else "failed", "expected": expected, "actual": actual})
    return verified


def _oeqa_statuses(value: object) -> list[str]:
    if isinstance(value, list):
        return [status for item in value for status in _oeqa_statuses(item)]
    if not isinstance(value, dict):
        return []
    statuses: list[str] = []
    for key in ("status", "result", "outcome"):
        raw = value.get(key)
        if isinstance(raw, str):
            statuses.append(raw.lower())
            break
    return statuses + [status for item in value.values() for status in _oeqa_statuses(item)]


def _oeqa_evidence(run_dir: Path, dry_run: bool) -> tuple[dict[str, object], bool]:
    files = sorted((run_dir / "oeqa/results").glob("**/*.json"))
    counts = {"pass": 0, "fail": 0, "skip": 0}
    for path in files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            counts["fail"] += 1
            continue
        for status in _oeqa_statuses(data):
            if status in {"pass", "passed", "success", "ok"}:
                counts["pass"] += 1
            elif status in {"skip", "skipped"}:
                counts["skip"] += 1
            elif status in {"fail", "failed", "error"}:
                counts["fail"] += 1
    evidence: dict[str, object] = {**counts, "result_files": [str(path) for path in files]}
    return evidence, dry_run or bool(files)


def _report(run_dir: Path, manifest: dict[str, object], records: list[dict[str, object]], summary: dict[str, object]) -> None:
    command_lines = "\n".join(f"- `{record['command']}` ({record['status']})" for record in records)
    selectors = " ".join(manifest["selectors"] if isinstance(manifest["selectors"], list) else [])
    oeqa = summary["oeqa"]
    text = "\n".join(("# Apollo OEQA validation report", "", f"- Status: `{summary['status']}`", f"- Machine: `{manifest['machine']}`", f"- Suite: `{manifest['suite']}`", f"- Case: `{manifest['case'] or 'all'}`", f"- Controller seam: `{manifest['controller']}`", f"- Selectors: `{selectors}`", "", "## Commands", command_lines, "", "## OEQA results", f"- Pass: `{oeqa['pass']}`", f"- Fail: `{oeqa['fail']}`", f"- Skip: `{oeqa['skip']}`", f"- Result files: `{len(oeqa['result_files'])}`", "", "## Evidence", f"- [manifest.json]({run_dir / 'manifest.json'})", f"- [parse-verification.json]({run_dir / 'parse-verification.json'})", f"- [summary.json]({run_dir / 'summary.json'})", f"- `oeqa/logs`, `oeqa/results`, and `oeqa/artifacts` are testimage evidence directories.", ""))
    (run_dir / "report.md").write_text(text, encoding="utf-8")


def _list(suites: dict[str, Suite]) -> int:
    for name, suite in suites.items():
        cases = " ".join(suite.cases) or "(no named cases)"
        print(f"{name}: {cases}")
    return 0


def _arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run selected Apollo OEQA testimage validation.")
    parser.add_argument("--machine", default="apollo-qvp")
    parser.add_argument("--test-suite")
    parser.add_argument("--test-case")
    parser.add_argument("--oeqa-selector", action="append", default=[])
    parser.add_argument("--out-dir")
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--parse-only", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = _arguments()
    root = Path(__file__).resolve().parents[2]
    config_dir = Path(__file__).resolve().parent
    try:
        profiles = load_profiles(config_dir / "profiles.json")
        suites = load_suites(config_dir / "suites.json")
        if args.list:
            return _list(suites)
        profile = profiles.get(args.machine)
        if profile is None:
            raise SelectionError(f"unknown machine '{args.machine}'")
        suite_name = args.test_suite or profile.default_suite
        suite = suites.get(suite_name)
        if suite is None:
            raise SelectionError(f"unknown test suite '{suite_name}'")
        if args.test_case is not None and not args.oeqa_selector and args.test_case not in suite.cases:
            raise SelectionError(f"unknown test case '{args.test_case}' for suite '{suite_name}'")
        selectors = resolve_selectors(suite, args.test_case, tuple(args.oeqa_selector))
        run_dir = _safe_run_dir(root, args.out_dir, args.machine)
    except (OSError, json.JSONDecodeError, SelectionError) as error:
        print(error, file=sys.stderr)
        return EXIT_USAGE
    for directory in (run_dir / "conf", run_dir / "logs", run_dir / "oeqa/logs", run_dir / "oeqa/results", run_dir / "oeqa/artifacts"):
        directory.mkdir(parents=True, exist_ok=True)
    log_path = run_dir / "runner.log"
    commands_path = run_dir / "commands.jsonl"
    conf_path = run_dir / "conf/oeqa-selected.conf"
    conf_path.write_text(_conf_text(args.machine, profile, run_dir, selectors), encoding="utf-8")
    manifest: dict[str, object] = {"machine": args.machine, "suite": suite_name, "case": args.test_case, "selectors": list(selectors), "controller": profile.controller, "image": profile.image, "distro": profile.distro, "conf": str(conf_path), "dry_run": args.dry_run, "parse_only": args.parse_only}
    _write_json(run_dir / "manifest.json", manifest)
    quoted_conf = shlex.quote(str(conf_path))
    quoted_machine = shlex.quote(args.machine)
    parse_command = (
        "source layers/poky/oe-init-build-env build >/dev/null && "
        f"MACHINE={quoted_machine} bitbake -R {quoted_conf} "
        f"-e {profile.image} | "
        "sed -n -e '/^TEST_SUITES=\"/p' -e '/^TEST_TARGET=\"/p'"
    )
    steps = [("parse", parse_command)]
    if not args.parse_only:
        steps.append(
            (
                "testimage",
                "source layers/poky/oe-init-build-env build >/dev/null && "
                f"MACHINE={quoted_machine} bitbake -R {quoted_conf} "
                f"{profile.image} -c testimage",
            )
        )
    passed = all(_run_step(name, command, root, run_dir, commands_path, args.dry_run, log_path) for name, command in steps)
    if passed:
        passed = _verify_parse(run_dir, profile, selectors, args.dry_run)
    records = [json.loads(line) for line in commands_path.read_text(encoding="utf-8").splitlines()]
    oeqa, results_present = _oeqa_evidence(run_dir, args.dry_run or args.parse_only)
    status = "PASS" if passed and results_present and oeqa["fail"] == 0 else "FAIL"
    if passed and not results_present:
        status = "BLOCKED"
    exit_code = 0 if status == "PASS" else EXIT_BLOCKED if status == "BLOCKED" else EXIT_FAIL
    summary: dict[str, object] = {"status": status, "exit_code": exit_code, "run_dir": str(run_dir), "selectors": list(selectors), "oeqa": oeqa, "commands": records}
    _write_json(run_dir / "summary.json", summary)
    (run_dir / "summary.txt").write_text(f"{status}: {args.machine} {suite_name} ({' '.join(selectors)})\n", encoding="utf-8")
    _report(run_dir, manifest, records, summary)
    print(f"RESULT: {status}")
    print(f"SUMMARY: {run_dir / 'summary.json'}")
    print(f"REPORT: {run_dir / 'report.md'}")
    print(f"LOG: {log_path}")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
