#
# SPDX-License-Identifier: MIT
#

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# Register this layer collection
BBFILE_COLLECTIONS += "meta-hsoc-apollo"
BBFILE_PATTERN_meta-hsoc-apollo = "^${LAYERDIR}/"

LAYERDEPENDS_meta-hsoc-apollo = "\
    core \
    meta-arm-auto-solutions \
"
LAYERSERIES_COMPAT_meta-hsoc-apollo = "walnascar"

HSOC_APOLLO_REPO_DIRECTORY = "${LAYERDIR}/../../"
